export { ThemeProvider } from '@material-ui/core/styles';
export {default as Button, baseButton as BaseButton} from './components/Button/Button';
export {default as Checkbox} from './components/Checkbox/Checkbox';
export {default as Card} from './components/Card/Card';
export {default as CardContent} from './components/Card/CardContent';
export {default as Typography} from './components/Typography/Typography';
export {default as Grid} from './components/Grid/Grid';
export {default as Paper} from './components/Paper/Paper';
export {default as Container} from './components/Container/Container';
export {default as globalTheme} from './globalTheme';